apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elitemart-backend.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elitemart-backend.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elitemart-backend.name" . }}
    spec:
      containers:
        - name: elitemart-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}

