kind: Service
apiVersion: v1
metadata: 
  name: apache-service
  namespace: apache
spec: 
  selector:
      app: apache
  ports:
    - protocol: TCP
      port: 80 # expose port in cluster
      targetPort: 80 # containerPort
  type: ClusterIP
  
